# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pxUZF_Tmcru6f57uU22iAR3Z8pqlO_AO
"""

import matplotlib.pyplot as plt
import numpy as np
x = np.array([18, 4])
qizlar = ["Qizlar"]
Bollar = ["Bollar"]
mylabels = qizlar + Bollar
plt.pie(x, labels=mylabels)
plt.show()